---
# Avalanchego version
avalanchego_version: 1.7.3
avalanchego_binary_name: "avalanchego-linux-amd64-v{{ avalanchego_version }}.tar.gz"
avalanchego_binary_url: "https://github.com/ava-labs/avalanchego/releases/download/v{{ avalanchego_version }}/{{ avalanchego_binary_name }}"

# Install directories
avalanche_root_dir: /opt/avalanche
avalanchego_install_dir: "{{ avalanche_root_dir }}/avalanchego"
avalanchego_conf_dir: "{{ avalanche_root_dir }}/conf"
avalanchego_db_dir: "{{ avalanche_root_dir }}/db"
avalanchego_certs_dir: "{{ avalanche_root_dir }}/certs"
avalanchego_log_dir: /var/log/avalanche/avalanchego

# User & network
avalanchego_user: avalanche
avalanchego_use_static_ip: yes
avalanchego_http_host: 127.0.0.1
avalanchego_http_port: 9650
avalanchego_staking_port: 9651

# Logging
avalanchego_log_level: info

# Consensus & bootstrapping
avalanchego_network_id: local
avalanchego_use_existing_certs: yes
avalanchego_snow_sample_size: 2
avalanchego_snow_quorum_size: 2
avalanchego_bootstrap_node_id: NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg

# Pre-funded account (only on local network)
avalanche_prefunded_username: cresus
avalanche_prefunded_password: g9KDa3X8g3Rm8mLP
avalanche_prefunded_private_key: PrivateKey-ewoqjP7PxY4yr3iLTpLisriqt94hdyDFNgchSxGGztUrTXtNN

# Subnets whitelist & VMs aliases
avalanche_whitelisted_subnets: ""
avalanche_vm_aliases:
  tGas3T58KzdjLHhBDMnH2TvrddhqTji5iZAMZ3RXs2NLpSnhH:
    - timestampvm
    - timestamp
  spePNvBxaWSYL2tB5e2xMmMNBQkXMN8z2XEbz1ML2Aahatwoc:
    - subnetevm
