---
- name: "P-Chain: call method {{ method }}"
  uri:
    url: "http://{{ avalanche_api_host }}:{{ avalanche_http_port }}/ext/bc/P"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "{{ method }}"
      params: "{{ params }}"
      id: 1
  register: call_res
  failed_when: call_res.json.error is defined

- block:
    - name: "P-Chain: wait for tx {{ call_res.json.result.txID }}"
      uri:
        url: "http://{{ avalanche_api_host }}:{{ avalanche_http_port }}/ext/bc/P"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: platform.getTxStatus
          params:
            txID: "{{ call_res.json.result.txID }}"
          id: 1
      register: tx_status_res
      until: tx_status_res.json.result.status == "Committed"
      failed_when: tx_status_res.json.result.status in ["Dropped", "Unknown"]
      retries: 3
      delay: 10

  rescue:
    - name: Retry call because tx status is 'Unknown'
      include_tasks: submit-transaction-p.yml
      when: (tx_status_res.json.result.status | default("Dropped")) == "Unknown"
