---
- name: Upload VM binaries to plugins dir
  copy:
    src: files/plugins/
    dest: "{{ avalanchego_plugins_dir }}/"
    mode: "0755"
    owner: "{{ avalanchego_user }}"
    group: "{{ avalanchego_user }}"
  notify: Restart avalanchego

- meta: flush_handlers
