version: "3.7"
x-services:
  avalanchego: &avalanchego
    image: "avaplatform/avalanchego:${AVALANCHEGO_VERSION:-v1.7.2}"
    command: [/avalanchego/start.sh]
    ports:
      - "9661:9650"
      - "9671:9651"
    networks:
      - avalanche
    volumes:
      - ./avalanchego/certs:/avalanchego/certs
      - ./avalanchego/start.sh:/avalanchego/start.sh
      - ./avalanchego/vm-aliases.json:/avalanchego/vm-aliases.json
      - ./avalanchego/plugins/timestampvm:/avalanchego/build/plugins/timestampvm
    depends_on:
      - avalanchego-1

networks:
  avalanche:

services:
  avalanchego-1:
    <<: *avalanchego
    container_name: avalanchego-1
    environment: { NODE_ID=1 }
    depends_on: []
  avalanchego-2:
    <<: *avalanchego
    container_name: avalanchego-2
    ports:
      - "9662:9650"
      - "9672:9651"
    environment: { NODE_ID=2 }
  avalanchego-3:
    <<: *avalanchego
    container_name: avalanchego-3
    ports:
      - "9663:9650"
      - "9673:9651"
    environment: { NODE_ID=3 }
  avalanchego-4:
    <<: *avalanchego
    container_name: avalanchego-4
    ports:
      - "9664:9650"
      - "9674:9651"
    environment: { NODE_ID=4 }
  avalanchego-5:
    <<: *avalanchego
    container_name: avalanchego-5
    ports:
      - "9665:9650"
      - "9675:9651"
    environment: { NODE_ID=5 }
