---
# HTTP API
avalanchego_http_host: 127.0.0.1
avalanchego_http_port: 9650

avalanchego_version: 1.7.3
avalanchego_plugins_dir: /opt/avalanche/avalanchego/avalanchego-v{{ avalanchego_version }}/plugins

# Subnet specs
avalanche_subnet_id: aUC7SX8QGVwsbwS4YNuavVTbinjJLrPjNNjdpZbbcFZZFSxFd
avalanche_subnet_control_username: control_key_1
avalanche_subnet_control_password: c0ntr0l_k3y_1

# VM specs
avalanche_vm_id: tGas3T58KzdjLHhBDMnH2TvrddhqTji5iZAMZ3RXs2NLpSnhH
avalanche_vm_alias: timestampvm
avalanche_vm_genesis_build_method: timestampvm.encode
avalanche_vm_genesis_json_key: bytes

# Blockchain specs
avalanche_blockchain_aliases:
  - timestamp
avalanche_blockchain_name: Timestamp Chain
avalanche_blockchain_genesis_data: Hello world
