---
- hosts: subnet_validators
  become: yes
  tasks:
    - import_role:
        name: avalanche-blockchain
        tasks_from: upload-vms.yml
      vars:
        avalanche_subnet_id: 2dCSRb8m4Sktr1kYST6AecNaXQD1qqWrD2CFvczJXP3ogbRAav

- hosts: subnet_validators[0]
  roles:
    - role: avalanche-blockchain
      vars:
        avalanche_subnet_id: 2dCSRb8m4Sktr1kYST6AecNaXQD1qqWrD2CFvczJXP3ogbRAav
