---
- hosts: subnet_validators
  become: yes
  tasks:
    - import_role:
        name: avalanche-blockchain
        tasks_from: upload-vms.yml
      vars:
        avalanche_subnet_id: yLBzHpdfhm66YdwXYFcHSsu4dBfRc5VgndmYqEn6JZ1ys1YwS

- hosts: subnet_validators[0]
  roles:
    - role: avalanche-blockchain
      vars:
        avalanche_subnet_id: yLBzHpdfhm66YdwXYFcHSsu4dBfRc5VgndmYqEn6JZ1ys1YwS
        avalanche_vm_id: spePNvBxaWSYL2tB5e2xMmMNBQkXMN8z2XEbz1ML2Aahatwoc
        avalanche_vm_alias: subnetevm
        avalanche_vm_genesis_build_method: subnetevm.buildGenesis
        avalanche_vm_genesis_json_key: genesisBytes
        avalanche_blockchain_aliases:
          - subnetevm
        avalanche_blockchain_name: Subnet EVM
        avalanche_blockchain_genesis_params:
          genesisData:
            config:
              chainId: 13213
              homesteadBlock: 0
              eip150Block: 0
              eip150Hash: "0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0"
              eip155Block: 0
              eip158Block: 0
              byzantiumBlock: 0
              constantinopleBlock: 0
              petersburgBlock: 0
              istanbulBlock: 0
              muirGlacierBlock: 0
              subnetEVMTimestamp: 0
              feeConfig:
                gasLimit: 8000000
                minBaseFee: 25000000000
                targetGas: 15000000
                baseFeeChangeDenominator: 36
                minBlockGasCost: 0
                maxBlockGasCost: 1000000
                targetBlockRate: 2
                blockGasCostStep: 200000
            alloc:
              8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC:
                balance: "0x295BE96E64066972000000"
            nonce: "0x0"
            timestamp: "0x0"
            extraData: "0x00"
            gasLimit: "0x7A1200"
            difficulty: "0x0"
            mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
            coinbase: "0x0000000000000000000000000000000000000000"
            number: "0x0"
            gasUsed: "0x0"
            parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
