---
- hosts: subnet_validators[0]
  tasks:
    - import_role:
        name: avalanche-network
        tasks_from: prefunded-account.yml
      when: avalanche_network_id == "local"

- hosts: subnet_validators[0]
  roles:
    - role: avalanche-subnet
