---
- name: Check if pre-funded account user already exists
  uri:
    url: "http://127.0.0.1:{{ avalanchego_http_port }}/ext/keystore"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: keystore.listUsers
      id: 1
  register: users_list_res

- name: Create pre-funded account user
  uri:
    url: "http://127.0.0.1:{{ avalanchego_http_port }}/ext/keystore"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: keystore.createUser
      params:
        username: "{{ avalanche_prefunded_username }}"
        password: "{{ avalanche_prefunded_password }}"
      id: 1
  when: avalanche_prefunded_username not in users_list_res.json.result.users
  register: users_create_res
  failed_when: users_create_res.json.error is defined

- name: Link pre-funded account to address on X-Chain
  uri:
    url: "http://127.0.0.1:{{ avalanchego_http_port }}/ext/bc/X"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: avm.importKey
      params:
        username: "{{ avalanche_prefunded_username }}"
        password: "{{ avalanche_prefunded_password }}"
        privateKey: "{{ avalanche_prefunded_private_key }}"
      id: 1
  register: import_key_res
  failed_when: import_key_res.json.error is defined

- name: Link pre-funded account to address on P-Chain
  uri:
    url: "http://127.0.0.1:{{ avalanchego_http_port }}/ext/bc/P"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: platform.importKey
      params:
        username: "{{ avalanche_prefunded_username }}"
        password: "{{ avalanche_prefunded_password }}"
        privateKey: "{{ avalanche_prefunded_private_key }}"
      id: 1
  register: import_key_res
  failed_when: import_key_res.json.error is defined
